version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: :arrow_up:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/backend" # Location of package manifests
    open-pull-requests-limit: 100
    schedule:
      interval: "daily"
    commit-message:
      prefix: ":arrow_up:"
  - package-ecosystem: npm
    directory: "/frontend/frontend-chatapp"
    open-pull-requests-limit: 100
    schedule:
      interval: "daily"
    commit-message:
      prefix: ":arrow_up:"
