version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/backend" # Location of package manifests
    open-pull-requests-limit: 100
    schedule:
      interval: "weekly"
      day: "wednesday"
