[tool.poetry]
name = "src"
version = "0.1.0"
description = ""
authors = ["WardM99 <wardmeersman@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.104.1"
uvicorn = "^0.24.0"
sqlmodel = "^0.0.14"
aiosqlite = "^0.19.0"
pytest-asyncio = "^0.23.2"
environs = "^9.5.0"
pytest-env = "^1.1.3"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
