[tool.poetry]
name = "src"
version = "0.1.0"
description = ""
authors = ["WardM99 <wardmeersman@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.104.1"
uvicorn = "^0.24.0"
sqlmodel = "^0.0.14"
aiosqlite = "^0.19.0"
environs = "^9.5.0"
pytest-env = "^1.1.3"
python-jose = "^3.3.0"
passlib = {extras = ["bycrypt"], version = "^1.7.4"}
python-multipart = "^0.0.6"
types-passlib = "^1.7.7.13"
types-python-jose = "^3.3.4.8"
aiohttp = "^3.9.1"
httpx = "^0.25.2"
requests = "^2.31.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"
pylint = "^3.0.2"
mypy = "^1.7"
pytest-asyncio = "^0.23.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
